apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: webapp-api-only-dockerized
spec:
  ports:
    - port: 5432
  selector:
    app: webapp-api-only-dockerized
    tier: postgres
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: webapp-api-only-dockerized
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webapp-api-only-dockerized
        tier: postgres
    spec:
      containers:
      - image: postgres:9.5.3
        name: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: mysecretpassword
        - name: POSTGRES_USER
          value: webapp-api-only-dockerized
        - name: POSTGRES_DB
          #value: webapp-api-only-dockerized_production
          value: webapp-api-only-dockerized_development
        #- name: PGDATA
        #  value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
          name: postgres
      #   volumeMounts:
      #     - name: postgres-persistent-storage
      #       mountPath: /var/lib/postgresql/data
      # volumes:
      #   - name: postgres-persistent-storage
      #     awsElasticBlockStore:
      #       volumeID: vol-fe268f4a
      #       fsType: ext4
